image: mcr.microsoft.com/dotnet/core/sdk:3.1

variables:
    solution: src\ExpenseTrackerWeb.sln

stages:
    - test
    - build
    - deploy

test:
    stage: test
    script: 
        - echo "-- Starting tests --"
        - dotnet test src
        - echo "-- Finished tests --"

build:
    stage: build
    script:
        - echo "-- Starting build --"
        - dotnet build src
        - echo "-- Finished build --"
    artifacts:
        paths:
            - src/bin/

deploy_test:
    stage: deploy
    script:
        - echo "-- Starting deploy to test --"
        - dotnet publish src/WebUI/WebUI.csproj -p:PublishProfileFullPath=~/src/WebUI/exptestWebDeploy.pubxml
    environment:
        name: test
        url: https://exptest.chakian.com
    only:
        - develop

deploy_prod:
    stage: deploy
    script:
        - echo "deploy to production"
    environment:
        name: prod
        url: https://harcama.chakian.com
    when: manual
    only:
        - master