image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build src"
    artifacts:
      paths:
        - src/bin/

test:
    stage: test
    script: 
        - "dotnet test src"