language: csharp
mono: none
dotnet: 3.1.302
script:
  - dotnet restore
  - dotnet build src/ExpenseTrackerWeb.sln
after_success:
  - echo 'Build finished'
notifications:
  email:
    on_success: never
    on_failure: always